### ISSUE TITLE
UDP section of the guide

### ISSUE THREAD

**Issue by eric-haibin-lin** [ofiwg/ofi-guide#14]
The programming guide is great! When will the UDP section be completed?

**Comment by shefty** [comment]
Thanks - the guide needs to be updated to match the latest version of the library.  It just hasn't been a priority relative to getting the actual code developed.  I can't give any time frame for when I will get back to the guide, other than to state that it's something that I would like to do.

**Comment by eric-haibin-lin** [comment]
Thanks. I also noticed TODOs for `Receive Contexts` and `Transmit Contexts`. Those might be more important than the `UDP` section I mentioned previously
